### ISSUE TITLE
Rewrite css paths

### ISSUE THREAD

**Issue by matthewp** [donejs/deploy#11]
We need to rewrite the paths to images in css. For example you might have:
### dev

```
pmo/
  header/
    header.css: url(../images/logo.png)
  images/
    logo.png
```
### prod

```
dist/
  bundles/
    header/
      header.css: url("../../images/logo.png")
  images/
    logo.png
```

**Comment by matthewp** [comment]
css rewrite: https://github.com/stealjs/steal-css/blob/master/css.js#L23

**Comment by matthewp** [comment]
The urls have already been rewritten by steal-tools at this point, so I think we can check if the file exists and is part of the files we are moving, and if so do the rewrite.

**Comment by mjstahl** [comment]
https://github.com/stealjs/steal-bundler

**Comment by mjstahl** [comment]
Fixed: https://github.com/stealjs/steal-bundler/commit/f152dd386fbbe55825f131724bc791128d7edcd0
