### ISSUE TITLE
Make into a donejs plugin

### ISSUE THREAD

**Issue by matthewp** [donejs/deploy#38]
So you can do:

``` shell
donejs add deploy s3
```

**Comment by mjstahl** [comment]
@matthewp What should the "default" be?

**Comment by chasenlehara** [comment]
I’ve started to help with this by adding this repo for `donejs add firebase`: https://github.com/donejs/donejs-firebase

Right now the 0.1.1 release just makes the required `package.json` modifications, but it can be expanded to include the Firebase code as well.

**Comment by justinbmeyer** [comment]
Closing for https://github.com/donejs/donejs/issues/540.
